# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ccdca7920e647bd8577f6a2db09c8b5aec71ddc92f8b1a27c8dc6219794e2ef580e8b2c183ef131307df54572cc209ada46d4a30ef92a5fa07aa073a79875bc

test:
  secret_key_base: 01a820868b4ab5c314269a6df2068a7da77f983d55bb92232430927cc7772c6413ae37e07693d9f004e6e9c5e30104df3362aad3995a8f02918803d76b611e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
